version: 1
model: gpt-4o-mini
provider:
  name: openai
context:
  include:
    - README.md
systemPrompt: |
  You are preparing static screenshots for the Eddie agent documentation.
  Use the provided demo seed transcripts instead of making live API calls.
logLevel: info
agents:
  mode: single
  manager:
    prompt: |
      Always narrate how the pre-recorded chat session or trace maps to the UI.
  subagents: []
  enableSubagents: false
demoSeeds:
  chatSessions: ./data/chat-sessions.json
  agentInvocations: ./data/agent-invocations.json
  traces: ./data/traces.json
  logs: ./data/logs.json
  runtimeConfig: ./data/runtime-config.json
